### ISSUE TITLE
Running action now fails

### ISSUE THREAD

**Issue by totosan** [Azure/aml-workspace#11] opened 2020-05-18 12:56 UTC
When running action, it fails since 15th of may. 
Container builds in workflow, but according action does fail with the message 
_"ls: cannot access 'code': No such file or directory"_

![image](https://user-images.githubusercontent.com/7992807/82215116-2ad32680-9917-11ea-8955-616b19c6416c.png)

From what I can see, is that the command ```ls``` in *entrypoint.sh* is in general correct. Removing ```ls``` from local build makes this working as expected. (Using nektos/act for local tests.)

This is the error message:
![image](https://user-images.githubusercontent.com/7992807/82486376-06c14200-9add-11ea-850a-c3b7a32afeed.png)

**Comment by marvinbuss** [comment] 2020-05-22 17:49
@totosan Thanks for submitting this. We will fix this today or tomorrow.

**Comment by totosan** [comment] 2020-05-22 18:34
I already made one with this PR #12 
Also please check following repos (will not spam issue lists :-) ):
- [aml-run](https://github.com/Azure/aml-run)
- [aml-compute](https://github.com/Azure/aml-compute)
- [aml-registermodel](https://github.com/Azure/aml-registermodel)

**Comment by marvinbuss** [comment] 2020-05-22 18:36
@totosan Sorry for the late reply. Are you running a special setup?
We ran a couple of tests and could not reproduce the issue. I would like to include your setup as a test case.

**Comment by totosan** [comment] 2020-05-22 18:45
No, no self-hosted. Nothing special. I was using suggested the yml from MAzure Machine Learning [example Repo](https://github.com/machine-learning-apps/ml-template-azure/blob/master/.github/workflows/train_deploy.yml).

**Comment by totosan** [comment] 2020-05-22 18:58
Maybe a silly question, but how can the secret be set in the PR - Integration test of your repo.  My Pr fails, because secret is not set.
btw. I am using a private repo with ubuntu:latest as image.

**Comment by aronchick** [comment] 2020-05-22 18:59
You have to set a secret in your repo - here's instructions https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by totosan** [comment] 2020-05-22 19:18
Hi @aronchick,
thx, the PR from my forked repo is running against this repo here. I set the secret at my repo, already. Maybe, I misunderstood something.

**Comment by marvinbuss** [comment] 2020-05-22 20:05
> Maybe a silly question, but how can the secret be set in the PR - Integration test of your repo. My Pr fails, because secret is not set.
> btw. I am using a private repo with ubuntu:latest as image.

@totosan  You have to add the secrets to this repo: https://github.com/totosan/aml-workspace

Can you please check the referenced branch and check whether it works as expected?
We will merge this to fix the issue. The same changes will be made to the other repos.

**Comment by marvinbuss** [comment] 2020-05-22 22:51
@totosan Can you please confirm whether the bugs are fixed in all `master` branches?
It is shown here how you can test the `master` branch of the AML Actions: https://github.com/marvinbuss/mlops/blob/be7a6470d76eb784c40d2bce46178d2d6cadbdd7/.github/workflows/train_deploy.yml#L16

I could no reproduce the error in my repo, but it would be great if you would provide some feedback. Draft releases will be made public once you confirm.

**Comment by marvinbuss** [comment] 2020-05-23 19:07
@totosan did you have a chance to test the changes in `master` of aml-workspace?

**Comment by totosan** [comment] 2020-05-23 19:18
Yeah, it's working like a charm. From my perspective, the bug is resolved. Thx a lot.

**Comment by marvinbuss** [comment] 2020-05-23 19:37
Great. I will release a new version tonight. You can switch back to v1 tomorrow. Thanks for submitting the bug.

Feel free to submit additional feature requests and bugs in the future.

**Comment by marvinbuss** [comment] 2020-05-23 22:13
I released an update to all AML Actions, which should fix the bug.
Please reopen the issue, if it persists.

**Closed** 2020-05-23 22:13 UTC
Labels: bug
